<footer id="contentinfo" class="body">
	<address id="about" class="vcard body">
		<span class="primary">
			<strong><a href="http://www.zf-boilerplate.com" target="_blank" class="fn url">ZF Boilerplate</a></strong>
		</span><!-- /.primary -->

		<span class="bio">Visit the official homepage for tutorials & help.</span>

	</address><!-- /#about -->
	<p>&copy; Copyright 2011 <a href="http://www.michael-romer.de" target="_blank">Michael Romer</a></p>
</footer><!-- /#contentinfo -->