<aside id="featured" class="body"><article>
	<hgroup>
    	<h2>This is ZF Boilerplate.</h2>
		<h3>Well done, it works!</h3>
	</hgroup>
	<p>ZF Boilerplate is a pre-packaged, pre-configured Zend Framework - based project blueprint for your enterprise grade PHP application. It combines state-of-the-art tools, frameworks and the best ideas to bootstrap your projects with nearly zero work. ZF Boilerplate ships with Doctrine 2, Symfony Dependency Injection, HTML 5 Boilerplate and a fully configured Virtual Machine that is managed by Vagrant and Chef - no need to install any deamons such as Apache or MySQL on your local box. And there is much more: Annotation based dependency injection, Module based Layouting, Scripts for creating the database and loading fixtures, Hudson/Jenkins Build Script and even more.</p>

</article></aside><!-- /#featured -->

<section id="content" class="body">
    <?php if (!$this->databaseError) { ?>
    <h3>Database Sample Records</h3>
    <p>With each page reload, a new record with random data is added to the database. The record title is randomly generated using a local service.</p>
	<ul>
	<?php foreach($this->data as $post) { ?>
        <li><?php echo $post; ?></li>
    <?php } ?>
    </ul><!-- /#posts-list -->
    <?php } else { ?>
    <h3>Database Setup</h3>
	<p>It looks like that the sample database hasn't been initialized yet. If you want to see Doctrine 2 in action, you will want to run the database and fixture setup script.</p>
    <ul>
        <li>SSH into the virtual box.
        <ul>
            <li>When running on linux, just execute "vagrant ssh" within the project directory.</li>
            <li>When on Windows, you will need to setup Putty first. For instructions please refer to <a href="http://vagrantup.com/docs/getting-started/setup/windows.html">Vagrant Windows Get Started Guide</a>.</li>
        </ul>
        </li>
        <li>Change to /vagrant/bin</li>
        <li>Run "php create-db-load-fixtures.php".</li>
        <li>Refresh this page.</li>
    </ul>
    <?php } ?>
</section><!-- /#content -->