<aside id="featured" class="body"><article>
	<hgroup>
    	<h2>This is ZF Boilerplate.</h2>
		<h3>Well done, it works!</h3>
	</hgroup>
	<p>ZF Boilerplate is a pre-packaged, pre-configured Zend Framework - based project blueprint for your enterprise grade PHP application. It combines state-of-the-art tools, frameworks and the best ideas to bootstrap your projects with nearly zero work. ZF Boilerplate ships with Doctrine 2, Symfony Dependency Injection, HTML 5 Boilerplate and a fully configured Virtual Machine that is managed by Vagrant and Chef - no need to install any deamons such as Apache or MySQL on your local box. And there is much more: Annotation based dependency injection, Module based Layouting, Scripts for creating the database and loading fixtures, Hudson/Jenkins Build Script and even more.</p>

</article></aside><!-- /#featured -->

<section id="content" class="body">
    <h3>Database check</h3>
	<ul>
        <li>Database ... <?php if (!$this->databaseError) { ?><strong>test ok!</strong> With each page-load, a dummy record is added to the database. Below you find a list of all records added.<?php } else { ?><strong>error</strong>. Looks like you did not yet set up the sample database schema. Not a big deal but if you want to see the database connection in action, you shall  <?php } ?> </li>
    </ul><!-- /#posts-list -->
    <h3>Data available</h3>
    <ul>
	<?php foreach($this->data as $post) { ?>
        <li><?php echo $post->getVorname(); ?></li>
    <?php } ?>
    </ul><!-- /#posts-list -->
</section><!-- /#content -->